[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dscreate"
authors = [{name = "Joél Collins", email = "joel.collins@flatironschool"}]
dynamic = ["version", "description"]